package com.countries.app.mappers;

import com.countries.app.pojos.Countries;
import com.countries.app.pojos.CountriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    long countByExample(CountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int deleteByExample(CountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int insert(Countries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int insertSelective(Countries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    List<Countries> selectByExample(CountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    Countries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int updateByExampleSelective(@Param("record") Countries record, @Param("example") CountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int updateByExample(@Param("record") Countries record, @Param("example") CountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int updateByPrimaryKeySelective(Countries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytable
     *
     * @mbg.generated Fri Feb 04 10:02:40 CST 2022
     */
    int updateByPrimaryKey(Countries record);
}